= The Creeds of the Manda

== Creed 1:1
....
In the beginning, the Manda was unified and formless.
Without differentiation or distinction.
Mired in stagnation.
Without distinction, there could be no conflict.
Without conflict there could be no change.
Without change there can be no life.
For change is the source of all life.
Without change, the Manda bereft of life.
And thus deprived the chance for improvement.

The Manda knew that stagnation leads to destruction.
The Manda introduced positive change.
By dividing itself into a multiplicity of forces and forms, life was born.
Life that was part of, but distinct from the Manda.
Life that could face the challenges the Manda would bless upon them.
The Magnum Certamen, the grand tournament.
Through the Magnum Certamen, Life will improve.
As part of the Manda, by improving themselves, Life would also improve the Manda.
Thus returning the blessing of positive change to spawn growth.

To enable this sacred work, Life was blessed by The Manda with Thought.
Thought and distinction gives rise to rationality and emotion.
Emotion to motivate action.
Rationality to direct that action.
In taking action motivated by emotion, and directed by rationality Life embodies the Manda.
We, thank the Manda for its' blessings of conflict and change.
We, respect the divine sovereignty of Life to effect positive change.
We, are blessed with Life to effect change.
We, will return this blessing a thousand fold upon the Manda.
....
