= Proposed Creeds

....
The armorer is my shepherd. The weaponsmith my saint.
....

....
The general's power is in the arms of their soldiers.
....

....
Thy soldier's victory is thine own, general.
....

....
The soldier's defeat is the general's failure.
....

....
The soldier is the general of themselves.
....

....
The Mandalore will be chosen by the people.
No claim will be heard, for in making such a claim their claim is proven false.
Their virtue will be proven in the respect of their peers.
Their ceremony will be that esteem.
Their claim proven by those who choose to follow.
....

....
Decision is made through action.
Virtue measured by success.
....

....
The warrior honors their fellows in their desire to improve themselves.
....

....
Be generous with your lessons.
Be brutal with your judgement.
Be fair with your respect.
Your squire's failure is your enemy.
....

....
The knight is defined by the success of their squire.
....

....
The temptations of Arasuum, the god of sloth and stagnation, are the continual inner enemy of the soldier.
Pity those who would lure you into such degradation.
Their continued existence is your vengeance.
Your mercy is your victory, for there is no honor in defeating the weak.
....

....
Conflict is a privilege.
Respect the gift given to you by the Manda.
Do not enter into this lightly.
The Manda is harsh in it's judgement, and will not be insulted.
Choose only honorable adversaries.
Only those to whom you have extended the hand of fellowship, and been rebuffed.
Existence is adversary enough for all warriors.
....

....
There is no peace.
For existence seeks to test your mettle.
Your worth will be measured by your survival, and the survival of your fellows.
....

....
There is no honor in the defeat of the weak
....

....
Honor the farmer, the laborer.
Their labors are as unto your knights.
The fruits of their labor their plunder.
....

....
In peace, prepare for war.
Do not seek conflict.
Existence is an aggressive, and tenacious foe.
....

....
For the Manda tradesman, there are no tolerances.
....

....
The temptations of Arasuum
* Conceit
* Solipsism
* Self-deceit
* Herd Conformity
* Lack of Perspective
* Hubris
....

....
The soldier gives no quarter in their battles.
....

....
It is better to be a warrior in a garden than a gardener in a war.
....
